const LIBRARY_COLORS = {
  'html5-qrcode': '#2563EB',
  'ZXing-js':     '#0284C7',
  'ZBar WASM':    '#0D9488',
  'ZXing WASM':   '#7C3AED',
  'BarcodeDetector': '#B45309',
};

const LIBRARY_BG = {
  'html5-qrcode': '#EFF6FF',
  'ZXing-js':     '#F0F9FF',
  'ZBar WASM':    '#F0FDFA',
  'ZXing WASM':   '#F5F3FF',
  'BarcodeDetector': '#FFFBEB',
};

const BARCODES  = ['B1', 'B2', 'B3', 'B4', 'B5'];
const LIBRARIES = ['html5-qrcode', 'ZXing-js', 'ZBar WASM', 'ZXing WASM', 'BarcodeDetector'];

function buildMarkdown(results, tester, deviceInfo, ranked) {
  const date = new Date().toLocaleString();
  const lines = [];

  lines.push(`# Barcode Integration Test — Results`);
  lines.push(``);
  lines.push(`**Tester:** ${tester.name}  `);
  lines.push(`**Company:** ${tester.company}  `);
  lines.push(`**Date:** ${date}  `);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## Device Info`);
  lines.push(``);
  lines.push(`| Property | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Browser | ${deviceInfo.browser} |`);
  lines.push(`| OS | ${deviceInfo.os} |`);
  lines.push(`| Device | ${deviceInfo.deviceType} |`);
  lines.push(`| Screen | ${deviceInfo.screenResolution} |`);
  lines.push(`| BarcodeDetector API | ${deviceInfo.barcodeDetectorSupported ? '✅ Supported' : '❌ Not supported'} |`);
  lines.push(`| User Agent | ${deviceInfo.userAgent} |`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## Library Rankings`);
  lines.push(``);
  lines.push(`| Rank | Library | Accuracy | Avg Time | Timeout Rate |`);
  lines.push(`|---|---|---|---|---|`);
  ranked.forEach(({ lib, stats }, i) => {
    const rank = i === 0 ? '🥇 1' : i === 1 ? '🥈 2' : i === 2 ? '🥉 3' : `${i + 1}`;
    lines.push(`| ${rank} | ${lib} | ${stats.accuracyPct}% | ${stats.avgTime ? `${stats.avgTime}ms` : '—'} | ${stats.failurePct}% |`);
  });
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## Scan Matrix`);
  lines.push(``);
  const header = `| Library | ${BARCODES.join(' | ')} |`;
  const sep    = `|---|${BARCODES.map(() => '---').join('|')}|`;
  lines.push(header);
  lines.push(sep);
  LIBRARIES.forEach(lib => {
    const cells = BARCODES.map(bc => {
      const r = results.find(x => x.library === lib && x.barcodeSlot === bc);
      if (!r) return '—';
      if (r.status === 'timeout') return `⏱ timeout`;
      const icon = r.userVerdict === 'correct' ? '✅' : r.userVerdict === 'wrong' ? '❌' : '?';
      return `${icon} ${r.responseTime}ms`;
    });
    lines.push(`| ${lib} | ${cells.join(' | ')} |`);
  });
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## Detailed Scan Log`);
  lines.push(``);
  LIBRARIES.forEach(lib => {
    const libResults = results.filter(r => r.library === lib);
    if (!libResults.length) return;
    lines.push(`### ${lib}`);
    lines.push(``);
    lines.push(`| Barcode | Status | Decoded Value | Response Time | Verdict |`);
    lines.push(`|---|---|---|---|---|`);
    libResults.forEach(r => {
      const verdict = r.userVerdict === 'correct' ? '✅ Correct' : r.userVerdict === 'wrong' ? '❌ Wrong' : '— n/a';
      lines.push(`| ${r.barcodeSlot} | ${r.status} | \`${r.decodedValue || 'N/A'}\` | ${r.responseTime}ms | ${verdict} |`);
    });
    lines.push(``);
  });
  lines.push(`---`);
  lines.push(``);
  lines.push(`*Generated by Barcode Integration Test v1.0*`);

  return lines.join('\n');
}

function downloadMarkdown(results, tester, deviceInfo, ranked) {
  const md       = buildMarkdown(results, tester, deviceInfo, ranked);
  const blob     = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url      = URL.createObjectURL(blob);
  const a        = document.createElement('a');
  const slug = (s) => s.trim().replace(/\s+/g, '-');
  const filename = `barcode-test_${slug(tester.name)}_${slug(tester.company)}_${new Date().toISOString().slice(0, 10)}.md`;
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function computeStats(results, library) {
  const libResults    = results.filter(r => r.library === library);
  const total         = libResults.length;
  const successes     = libResults.filter(r => r.status === 'success').length;
  const timeouts      = libResults.filter(r => r.status === 'timeout').length;
  const correct       = libResults.filter(r => r.userVerdict === 'correct').length;
  const wrong         = libResults.filter(r => r.userVerdict === 'wrong').length;
  const successResults = libResults.filter(r => r.status === 'success');
  const avgTime       = successResults.length > 0
    ? Math.round(successResults.reduce((s, r) => s + r.responseTime, 0) / successResults.length)
    : null;
  const accuracyPct   = total > 0 ? Math.round((correct / total) * 100) : 0;
  const failurePct    = total > 0 ? Math.round((timeouts / total) * 100) : 0;
  return { total, successes, timeouts, correct, wrong, avgTime, accuracyPct, failurePct };
}

function rankLibraries(results) {
  return LIBRARIES.map(lib => {
    const s = computeStats(results, lib);
    const speedScore = s.avgTime ? Math.max(0, 100 - (s.avgTime / 50)) : 0;
    const score = (s.accuracyPct * 0.6) + (speedScore * 0.4);
    return { lib, score, stats: s };
  }).sort((a, b) => b.score - a.score);
}

const card = {
  background: '#FFFFFF', border: '1px solid #E5E7EB',
  borderRadius: 14, padding: 24, marginBottom: 20,
  boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
};

const sectionLabel = {
  fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 600,
  color: '#9CA3AF', letterSpacing: 1.5, marginBottom: 18,
};

export default function ResultsScreen({ results, tester, deviceInfo, onSendResults }) {
  const ranked  = rankLibraries(results);
  const winner  = ranked[0];

  return (
    <div style={{ minHeight: '100vh', background: '#F4F6F9', padding: '40px 20px' }}>
      <div style={{ maxWidth: 760, margin: '0 auto' }} className="fade-up">

        {/* Header */}
        <div style={{ marginBottom: 32 }}>
          <div style={{
            display: 'inline-block', marginBottom: 12,
            fontFamily: 'JetBrains Mono, monospace', fontSize: 10, fontWeight: 600,
            color: '#16A34A', letterSpacing: 2,
            background: '#F0FDF4', border: '1px solid #BBF7D0',
            borderRadius: 4, padding: '3px 10px',
          }}>TEST COMPLETE</div>
          <h2 style={{
            fontSize: 32, fontWeight: 800, color: '#111827',
            fontFamily: 'Syne, sans-serif', marginBottom: 6,
          }}>Results Summary</h2>
          <p style={{ color: '#6B7280', fontSize: 14 }}>
            {tester.name} · {tester.company} · {results.length} scans completed
          </p>
        </div>

        {/* Winner card */}
        <div style={{
          background: '#FFFFFF',
          border: '1px solid #BBF7D0',
          borderLeft: '4px solid #16A34A',
          borderRadius: 14, padding: 24, marginBottom: 20,
          display: 'flex', alignItems: 'center', gap: 20,
          boxShadow: '0 2px 8px rgba(22,163,74,0.08)',
        }}>
          <div style={{
            width: 56, height: 56, borderRadius: 12,
            background: '#F0FDF4', display: 'flex',
            alignItems: 'center', justifyContent: 'center',
            fontSize: 28, flexShrink: 0,
          }}>🏆</div>
          <div>
            <p style={{
              fontSize: 10, fontFamily: 'JetBrains Mono, monospace',
              color: '#16A34A', letterSpacing: 2, marginBottom: 4, fontWeight: 600,
            }}>BEST PERFORMER</p>
            <p style={{ fontSize: 24, fontWeight: 800, color: '#111827', fontFamily: 'Syne, sans-serif' }}>
              {winner.lib}
            </p>
            <p style={{ color: '#6B7280', fontSize: 13, marginTop: 3 }}>
              {winner.stats.accuracyPct}% accuracy ·{' '}
              {winner.stats.avgTime ? `${winner.stats.avgTime}ms avg` : 'N/A'} ·{' '}
              {winner.stats.failurePct}% timeout rate
            </p>
          </div>
        </div>

        {/* Library rankings */}
        <div style={card}>
          <p style={sectionLabel}>Library Rankings</p>
          {ranked.map(({ lib, stats }, i) => {
            const color = LIBRARY_COLORS[lib] || '#6B7280';
            const bg    = LIBRARY_BG[lib] || '#F9FAFB';
            return (
              <div key={lib} style={{
                display: 'flex', alignItems: 'center', gap: 14,
                marginBottom: i < ranked.length - 1 ? 12 : 0,
                padding: '12px 14px',
                background: i === 0 ? '#F0FDF4' : '#F9FAFB',
                borderRadius: 10,
                border: i === 0 ? '1px solid #BBF7D0' : '1px solid #F3F4F6',
              }}>
                {/* Rank badge */}
                <div style={{
                  width: 28, height: 28, borderRadius: '50%', flexShrink: 0,
                  background: i === 0 ? '#16A34A' : '#E5E7EB',
                  color: i === 0 ? '#FFFFFF' : '#6B7280',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 12, fontWeight: 800, fontFamily: 'JetBrains Mono, monospace',
                }}>
                  {i === 0 ? '★' : i + 1}
                </div>

                {/* Name + bar */}
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{ fontWeight: 700, fontSize: 14, color: '#111827', marginBottom: 5 }}>{lib}</p>
                  <div style={{ height: 5, background: '#E5E7EB', borderRadius: 3 }}>
                    <div style={{
                      height: '100%', borderRadius: 3,
                      width: `${stats.accuracyPct}%`,
                      background: color, transition: 'width 0.8s ease',
                    }} />
                  </div>
                </div>

                {/* Stats */}
                <div style={{
                  display: 'flex', gap: 20, flexShrink: 0,
                  fontFamily: 'JetBrains Mono, monospace', fontSize: 11,
                }}>
                  <div style={{ textAlign: 'center' }}>
                    <p style={{ color: '#16A34A', fontWeight: 700 }}>{stats.accuracyPct}%</p>
                    <p style={{ color: '#9CA3AF', fontSize: 10, marginTop: 1 }}>accuracy</p>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <p style={{ color: '#2563EB', fontWeight: 700 }}>
                      {stats.avgTime ? `${stats.avgTime}ms` : '—'}
                    </p>
                    <p style={{ color: '#9CA3AF', fontSize: 10, marginTop: 1 }}>avg time</p>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <p style={{ color: stats.failurePct > 40 ? '#DC2626' : '#9CA3AF', fontWeight: 700 }}>
                      {stats.failurePct}%
                    </p>
                    <p style={{ color: '#9CA3AF', fontSize: 10, marginTop: 1 }}>timeouts</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Scan matrix */}
        <div style={{ ...card, overflowX: 'auto' }}>
          <p style={sectionLabel}>Scan Matrix — Library × Barcode</p>
          <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 500 }}>
            <thead>
              <tr>
                <th style={{
                  textAlign: 'left', padding: '8px 12px',
                  fontFamily: 'JetBrains Mono, monospace', fontSize: 11, fontWeight: 600,
                  color: '#9CA3AF', borderBottom: '1px solid #F3F4F6',
                }}>Library</th>
                {BARCODES.map(b => (
                  <th key={b} style={{
                    textAlign: 'center', padding: '8px 12px',
                    fontFamily: 'JetBrains Mono, monospace', fontSize: 11, fontWeight: 600,
                    color: '#9CA3AF', borderBottom: '1px solid #F3F4F6',
                  }}>{b}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {LIBRARIES.map((lib, rowIdx) => (
                <tr key={lib}>
                  <td style={{
                    padding: '10px 12px', fontWeight: 600,
                    color: LIBRARY_COLORS[lib] || '#374151',
                    borderBottom: rowIdx < LIBRARIES.length - 1 ? '1px solid #F9FAFB' : 'none',
                    fontFamily: 'JetBrains Mono, monospace', fontSize: 11,
                  }}>{lib}</td>
                  {BARCODES.map(bc => {
                    const r = results.find(x => x.library === lib && x.barcodeSlot === bc);
                    if (!r) return (
                      <td key={bc} style={{
                        textAlign: 'center', padding: '10px 12px',
                        color: '#D1D5DB', borderBottom: rowIdx < LIBRARIES.length - 1 ? '1px solid #F9FAFB' : 'none',
                        fontSize: 11, fontFamily: 'JetBrains Mono, monospace',
                      }}>—</td>
                    );
                    const icon  = r.status === 'timeout' ? '⏱' : r.userVerdict === 'correct' ? '✓' : r.userVerdict === 'wrong' ? '✗' : '?';
                    const color = r.status === 'timeout' ? '#EA580C' : r.userVerdict === 'correct' ? '#16A34A' : '#DC2626';
                    return (
                      <td key={bc} style={{
                        textAlign: 'center', padding: '10px 12px',
                        borderBottom: rowIdx < LIBRARIES.length - 1 ? '1px solid #F9FAFB' : 'none',
                      }}>
                        <span style={{ fontSize: 14, color, fontWeight: 700 }}>{icon}</span>
                        {r.status !== 'timeout' && (
                          <p style={{
                            fontSize: 10, color: '#9CA3AF',
                            fontFamily: 'JetBrains Mono, monospace', marginTop: 2,
                          }}>{r.responseTime}ms</p>
                        )}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', gap: 12, marginBottom: 40 }}>
          <button
            onClick={() => downloadMarkdown(results, tester, deviceInfo, ranked)}
            style={{
              flex: 1, padding: '15px',
              background: '#FFFFFF', border: '1.5px solid #E5E7EB',
              borderRadius: 12, color: '#374151', fontSize: 15, fontWeight: 600,
              cursor: 'pointer', fontFamily: 'Inter, sans-serif',
              boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            }}
          >
            ↓ Download .md
          </button>
          <button
            onClick={onSendResults}
            style={{
              flex: 1, padding: '15px',
              background: '#2563EB', border: 'none', borderRadius: 12,
              color: '#FFFFFF', fontSize: 15, fontWeight: 700,
              cursor: 'pointer', fontFamily: 'Syne, sans-serif',
              boxShadow: '0 4px 12px rgba(37,99,235,0.28)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            }}
          >
            ✉ Send to Fynd
          </button>
        </div>
      </div>
    </div>
  );
}
